<?php
  /**
   * Implementation of hook_form_alter().
   *
   * The function is named modulename_form_alter.
   */
  /*function locazione_form_alter(&$form, $form_state, $form_id) {
    // Normally a switch is used because you may want to alter more than
    // one form and it is easy to add a new case for each form.
    switch ($form_id) {
      // This is our form ID.
      case 'page_node_form':
        // Our kickin' mods go here.

	$form['regione'] = array(
            '#type' => 'select',
            '#title' => t('Regione'),
            '#weight' => -99,
	    '#default_value' => variable_get('feed_item_length','teaser'),
            '#options' => array(
              'lombardia' => t('Lombardia'),
	      'sardegna' => t('Sardegna'),            
  	     ),
        );
        $form['#submit'][] = 'locazione_submit';
        //$form['#submit'][] = 'locazione_validate';
	
	// fine delle istruzioni
      break;
    }	
  }


*/

/*function locazione_submit($form, &$form_state) {   
	die; 
	$regione = $form_state['values']['regione'];
	print_r($form_state);

	//form_set_value( array('#parents' => array('values','field_prova','0','values')), 'tacca',$form_state);
	form_set_value( array('#parents' => array('field_prova','0','value')), 'tacca',$form_state);     
  } 
*/



/*function create_form_regions($regions,$weight) { 
	$options = array();
	foreach ($regions as $regione) {
		$options[$regione['regione_id']] = $regione['regione_nome'];
	}

	

	$my_form = array (
  '#type' => 'select',
  '#title' => t('Regione'),
  '#weight' => '-8.993963',
  /*'#options' => array (
    'sardegna' => t('Sardegna'),
    'lombardia' => t('Lombardia'),
  '#options' => $options,
  '#default_value' => $regione_default_value,
);

return $my_form;

}*/

/*function create_form_provinces($regione_id, $regione_nome,$province_lista,$weight) {

        $options = array();
	
	foreach ($province_lista as $province) {
		$options[$province['provincia_id']]= $province['provincia_nome'];
	}
      
	$my_form = array (
	  '#type' => 'select',
	  '#title' => t('Province '.$regione_nome),
	  '#options' => $options,
	  '#weight' => -8.993962,
	  '#default_value' => $dummy,

	  // 2. This ensures that the element will be processed by ctools dependent
	  '#process' => array('ctools_dependent_process'),

	  // 3. This instructs ctools_dependent which other elements this
	  //     should depend on. It has the following format:
	  //     #dependency => array('id-of-element-to-depend-on' => array('any_value', 'will', 'trigger', 'me'))
	  '#dependency' => array('edit-regione' => array($regione_id)),
	);

  return $my_form;
}*/

/*function create_form_cities($region_id,$province_id,$cities_list,$weight) {

	$options = array();
	foreach ($cities_list as $citta) {
		$options[$citta['comune_id']] = $citta['comune_nome'];
	}
	
	$my_form = array (
	  '#type' => 'select',
	  '#title' => t('Comuni '.$province),
	  '#options' => $options,	
	  '#weight' => -8.993961,  
	  //'#fieldset => multistep-group_mandataria,
	  '#default_value' => $dummy_comune,	  
	  '#process' => array('ctools_dependent_process'),
	  '#dependency_count' => 2,
 	  '#dependency' => array('edit-provincia-'.$region_id => array($province_id), 'edit-regione' => array($region_id)),
	  //'#dependency' => array('edit-province-lombardia' => array('milano'), 'edit-regione' => array('lombardia'))
	);

  return $my_form;
}*/


function locazione_form_alter(&$form, $form_state, $form_id) {
//echo $form_id;
if ($form_id == 'user_register') {
	drupal_set_title(t('Registrazione utente')); 
}

if ($form_id == 'profile_node_form') {
	drupal_set_title(t('Modifica profilo'));
}

if ($form_id == 'user_pass') {
	drupal_set_title(t('Recupero credenziali'));
}

/*if ($form_id == 'user_register') { /*
	$form['dati_anagrafici'] = array(
  	'#value' => t('<div class="etichette">Dati anagrafici</div>'),
  	'#weight' => ('-99'),);

	$form['dati_mandataria'] = array(
  	'#value' => t('<div class="etichette">Mandataria</div>'),
  	'#weight' => ('-8'),);

	$form['credenziali_accesso'] = array(
  	'#value' => t('<div class="etichette">Credenziali di accesso</div>'),
  	'#weight' => ('0'),);
}

// solo quando si modifica utente
if ($form_id == 'profile_node_form' AND $form_id !== 'user_register') { 
	$form['aa'] = array(
  	'#value' => t('<div class="etichette">Dati anagrafici</div>'),
  	'#weight' => ('-99'),);

	/*$form['ab'] = array(
  	'#value' => t('<div class="etichette">Mandataria</div>'),
  	'#weight' => ('7'),);*/

	/*if ($form_id == 'user register') { 
		$form['ac'] = array(
  		'#value' => t('<div class="etichette">Credenziali di accesso</div>'),
  		'#weight' => ('18'),);}
}


if ($form_id == 'user_register') { 
	$form['dati'] = array(
  	'#value' => t('<div class="etichette">Dati anagrafici</div>'),
  	'#weight' => ('-100'),);

	/*$form['manda'] = array(
  	'#value' => t('<div class="etichette">Mandataria</div>'),
  	'#weight' => ('-9'),);

	$form['credenziali'] = array(
  	'#value' => t('<div class="etichette">Credenziali di accesso</div>'),
  	'#weight' => ('0'),);

	
}


// prima c'erano 2 if
 if ($form_id == 'user_register' OR $form_id == 'profile_node_form') { 

      // This is our form ID.

     // case 'user_register':

//$form['submit2'] = $form['submit'];
$form['submit']['#weight'] = 99;   

ctools_include('dependent');

//include("lista.php");

/*$regions = array (
    'sardegna' => t('Sardegna'),
    'lombardia' => t('Lombardia')
  );*/
/*
$sql = "SELECT regione_id, regione_nome FROM regioni ORDER BY regione_nome";
$prendi_regioni = db_query($sql);


$sql1 = "SELECT regione_nome FROM regioni ORDER BY regione_nome";
$sergio = db_query($sql1);
while ($sergio1 = db_fetch_array($sergio)) {
	$stampa = ucfirst(strtolower($sergio1['regione_nome']));
	echo "$stampa<br>";
}



$regions = array();

while ($regioni = db_fetch_array($prendi_regioni)) {
	$regions[] = $regioni;	
}

$form['regione'] = create_form_regions($regions,$weight);


/*$province=array(
	'sardegna' => array (
    		'cagliari' => array('cagliari','quartu','monserrato'),
    		'sassari' =>  array('sassari','ossi','tissi'),
  		),
	'lombardia' => array (
    		'milano' => array('milano','monza','piacenza'),
    		'mantova' => array('mantova','poggibonzi')
  		)
	);

foreach ($regions as $regione) {
	$form_name = "provincia_".$regione['regione_id'];
	//query per popolare $provinces_from_db	

	$sql = "SELECT provincia_id, provincia_nome FROM province WHERE regione_id = $regione[regione_id] ORDER BY provincia_nome";
	$prendi_province = db_query($sql);
	while ($province = db_fetch_array($prendi_province)) {
		$province_lista[] = $province;	
	}  

	//$provinces_from_db=array_keys ($province["$region_id"]);

	$form[$form_name] = create_form_provinces($regione['regione_id'],$regione['regione_nome'],$province_lista,$weight);
	
	foreach($province_lista as $province) {
		//query per popolare $cities_from_db
		
		$sql = "SELECT comune_id, comune_nome FROM comuni WHERE provincia_id = $province[provincia_id]";
		$prendi_comuni = db_query($sql);
		
		while ($comuni = db_fetch_array($prendi_comuni)) {
			$comuni_lista[] = $comuni;	} 

		//$cities_list=$province["$region_id"]["$province_id"];
		$form_name='comuni_'.$province['provincia_id'];
		$form[$form_name]=create_form_cities($regione['regione_id'],$province['provincia_id'],$comuni_lista,$weight);	
		unset($comuni_lista);	
	
	}
	unset($province_lista);

	
}



//print_r($form);
//die;
//break;

}

}*/

?>
